import type { IRecordMedications } from "@/types/RecordMedicationsType";
import type { IRecord } from "@/types/RecordType";
import type { IVitalSigns } from "@/types/VitalSignsType";
import { Button } from "../../shadcn/button";

function ConsultationPrintView({
  record,
  vitalSigns,
  recordMedications,
}: {
  record: IRecord;
  vitalSigns: IVitalSigns;
  recordMedications: IRecordMedications[];
}) {
  return (
    <div className="mx-auto w-[210mm] bg-white p-10 text-black print:w-full print:p-6">
      {/* HEADER */}
      <div className="mb-6 border-b pb-3 text-center">
        <h1 className="text-xl font-bold">CLINIC NAME</h1>
        <p className="text-sm">Medical Consultation Report</p>
      </div>

      {/* CONSULTATION DETAILS */}
      <section className="mb-6">
        <h2 className="mb-2 border-b text-sm font-bold">
          Consultation Details
        </h2>

        <p className="text-sm">
          <span className="font-semibold">Symptoms:</span> {record?.symptoms}
        </p>
        <p className="text-sm">
          <span className="font-semibold">Signs:</span> {record?.signs}
        </p>
        <p className="text-sm">
          <span className="font-semibold">Diagnosis:</span> {record?.diagnosis}
        </p>
      </section>

      {/* VITAL SIGNS */}
      <section className="mb-6">
        <h2 className="mb-2 border-b text-sm font-bold">Vital Signs</h2>

        <div className="grid grid-cols-3 gap-4 text-sm">
          <p>
            <span className="font-semibold">BP:</span>{" "}
            {vitalSigns?.bloodPressureSystolic}/
            {vitalSigns?.bloodPressureDiastolic}
          </p>
          <p>
            <span className="font-semibold">Temp:</span>{" "}
            {vitalSigns?.temperature}°C
          </p>
          <p>
            <span className="font-semibold">Weight:</span>{" "}
            {vitalSigns?.weightKg} kg
          </p>
        </div>
      </section>

      {/* MEDICATIONS */}
      <section className="mb-6">
        <h2 className="mb-2 border-b text-sm font-bold">Medications</h2>

        {recordMedications?.map((med, i) => (
          <div key={med.id} className="mb-3 text-sm">
            <p className="font-semibold">
              {i + 1}. {med.name}
            </p>
            <p>Dosage: {med.dosage}</p>
            <p>Frequency: {med.frequency}</p>
            <p>Duration: {med.durationDays} days</p>
            <p>Instructions: {med.instructions}</p>
          </div>
        ))}
      </section>

      {/* SIGNATURE */}
      <div className="mt-10 text-sm">
        <p>Doctor’s Signature: __________________________</p>
      </div>

      {/* FOOTER */}
      <div className="mt-10 text-center text-xs text-gray-500">
        Generated by Clinic System
      </div>

      <div className="flex justify-end print:hidden">
        <Button
          onClick={() => window.print()}
          className="mt-4 cursor-pointer text-center print:hidden"
        >
          Print Report
        </Button>
      </div>
    </div>
  );
}

export default ConsultationPrintView;
